# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  lepinguregister-app:
    image: lepinguregister
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lepinguregister-postgresql:5432/lepinguregister
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://lepinguregister-postgresql:5432/lepinguregister
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8080:8080
  lepinguregister-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/lepinguregister/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lepinguregister
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5432:5432
